---
- job:
    name: repoxplorer-unittests
    parent: base
    description: Base job for repoXplorer unittests
    run: playbooks/unittests.yaml

- job:
    name: repoxplorer-unittests-py27
    parent: repoxplorer-unittests
    description: repoXplorer unittests for Python 2.7
    vars:
      tox_target: py27
    nodeset:
      nodes:
        - name: test-node
          label: dib-centos-7

- job:
    name: repoxplorer-unittests-py37
    parent: repoxplorer-unittests
    description: repoXplorer unittests for Python 3.7
    vars:
      tox_target: py37
    nodeset:
      nodes:
        - name: test-node
          label: runc-fedora-29

- project:
    name: repoxplorer
    check:
      jobs:
        - repoxplorer-unittests-py27
        - repoxplorer-unittests-py37
    gate:
      jobs:
        - repoxplorer-unittests-py27
        - repoxplorer-unittests-py37
