---
- job:
    name: repoxplorer-tox-py37
    parent: tox
    description: repoXplorer unittests for Python 3.7
    pre-run: playbooks/playbooks/elasticinstall.yaml
    vars:
      tox_envlist: py37
    nodeset:
      nodes:
        - name: test-node
          label: dib-fedora-28-minimal

- project:
    check:
      jobs:
        - repoxplorer-tox-py37
    gate:
      jobs:
        - repoxplorer-tox-py37
