---
- job:
    name: test-k1s
    parent: base
    description: Test k1s
    run: playbooks/run.yaml
    nodeset:
      nodes:
        - name: pod-fedora-30
          label: pod


- project:
    check:
      jobs:
        - test-k1s
