---
- job:
    name: repoxplorer-unittests
    parent: base
    description: This is running the unittests for this project
    run: playbooks/unittests.yaml
    nodeset:
      nodes:
        - name: test-node
          label: dib-centos-7

- project:
    name: repoxplorer
    check:
      jobs:
        - repoxplorer-unittests
    gate:
      jobs:
        - repoxplorer-unittests
