---
- job:
    name: repoxplorer-base
    parent: base
    description: repoXplorer base job
    pre-run:
      - playbooks/start-tracer.yaml
      - playbooks/deps-install.yaml
    post-run:
      - playbooks/stop-tracer.yaml
    run: playbooks/tox.yaml
    roles:
      - zuul: software-factory/ci-tracer
    nodeset:
      nodes:
        - name: test-node
          label: cloud-fedora-30

- job:
    name: repoxplorer-tox-py36-el6
    parent: repoxplorer-base
    description: repoXplorer unittests for Python 3.7
    pre-run: playbooks/elastic6-install.yaml
    vars:
      tox_target: py37

- job:
    name: repoxplorer-tox-py37-el6
    parent: repoxplorer-base
    description: repoXplorer unittests for Python 3.7
    pre-run: playbooks/elastic6-install.yaml
    vars:
      tox_target: py37

- job:
    name: repoxplorer-tox-py37-el5
    parent: repoxplorer-base
    description: repoXplorer unittests for Python 3.7
    pre-run: playbooks/elastic5-install.yaml
    vars:
      tox_target: py37

- job:
    name: repoxplorer-tox-pep8
    parent: repoxplorer-base
    description: repoXplorer flake8 validation
    vars:
      tox_target: pep8

- project:
    check:
      jobs:
        - repoxplorer-tox-py37-el6
    gate:
      jobs:
        - repoxplorer-tox-pep8
        - repoxplorer-tox-py37-el5
        - repoxplorer-tox-py36-el6
        - repoxplorer-tox-py37-el6
