---
- job:
    name: repoxplorer-base
    parent: base
    description: repoXplorer base job
    pre-run: playbooks/deps-install.yaml
    run: playbooks/tox.yaml
    nodeset:
      nodes:
        - name: test-node
          label: cloud-fedora-31

- job:
    name: repoxplorer-tox-py36-el6
    parent: repoxplorer-base
    description: repoXplorer unittests for Python 3.7
    pre-run: playbooks/elastic6-install.yaml
    vars:
      tox_target: py37

- job:
    name: repoxplorer-tox-py37-el6
    parent: repoxplorer-base
    description: repoXplorer unittests for Python 3.7
    pre-run: playbooks/elastic6-install.yaml
    vars:
      tox_target: py37

- job:
    name: repoxplorer-tox-py37-el5
    parent: repoxplorer-base
    description: repoXplorer unittests for Python 3.7
    pre-run: playbooks/elastic5-install.yaml
    vars:
      tox_target: py37

- job:
    name: repoxplorer-tox-pep8
    parent: repoxplorer-base
    description: repoXplorer flake8 validation
    vars:
      tox_target: pep8

- job:
    name: repoxplorer-tox-py36-el7
    parent: repoxplorer-base
    description: repoXplorer unittests for Python 3.6 and Elasticsearch 7
    pre-run: playbooks/elastic7-install.yaml
    vars:
      tox_target: py36

- job:
    name: repoxplorer-tox-py37-el7
    parent: repoxplorer-base
    description: repoXplorer unittests for Python 3.7 and Elasticsearch 7
    pre-run: playbooks/elastic7-install.yaml
    vars:
      tox_target: py37

- project:
    check:
      jobs:
        - repoxplorer-tox-pep8
        - repoxplorer-tox-py37-el5
        - repoxplorer-tox-py36-el6
        - repoxplorer-tox-py37-el6
        - repoxplorer-tox-py36-el7
        - repoxplorer-tox-py37-el7
    gate:
      jobs:
        - repoxplorer-tox-pep8
        - repoxplorer-tox-py37-el5
        - repoxplorer-tox-py36-el6
        - repoxplorer-tox-py37-el6
        - repoxplorer-tox-py37-el7
