---
- job:
    name: repoxplorer-base
    parent: base
    description: repoXplorer base job
    pre-run: playbooks/deps-install.yaml
    run: playbooks/tox.yaml
    nodeset:
      nodes:
        - name: test-node
          label: dib-fedora-28-minimal

- job:
    name: repoxplorer-tox-py37
    parent: repoxplorer-base
    description: repoXplorer unittests for Python 3.7
    pre-run: playbooks/elastic-install.yaml
    vars:
      tox_target: py37

- job:
    name: repoxplorer-tox-pep8
    parent: repoxplorer-base
    description: repoXplorer flake8 validation
    vars:
      tox_target: pep8

- project:
    check:
      jobs:
        - repoxplorer-tox-pep8
        - repoxplorer-tox-py37
    gate:
      jobs:
        - repoxplorer-tox-pep8
        - repoxplorer-tox-py37
