---
- job:
    name: test-k1s
    parent: base
    description: Test k1s
    run: playbooks/run.yaml
    nodeset:
      nodes:
        - name: pod
          label: pod-fedora-30


- project:
    check:
      jobs:
        - test-k1s
