---
- job:
    name: atestjob
    run: playbooks/test.yaml
    branches: rpm-master
    nodeset:
      nodes:
        - name: container
          label: zuul-worker-f34

- project:
    check:
      jobs:
        - atestjob
