---
- hosts: test-node
  tasks:
    - name: "Install some distro required packages"
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - which
        - python3-tox
      become: true
