---
- hosts: test-node
  tasks:
    - name: "Install some distro required for Elastic"
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - which
        - java-1.8.0-openjdk
      become: true
    - name: Extract ElasticSearch 7.7.x archive
      unarchive:
        src: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.7.1-linux-x86_64.tar.gz
        dest: "{{ ansible_user_dir }}"
        remote_src: yes
    - name: Remove Xms/Xmx from default JVM options file
      lineinfile:
        path: "{{ ansible_user_dir }}/elasticsearch-7.7.1/config/jvm.options"
        state: absent
        regexp: '^-Xm.*$'
    - name: Start ElasticSearch
      command: "{{ ansible_user_dir }}/elasticsearch-7.7.1/bin/elasticsearch -d"
      environment:
        ES_JAVA_OPTS: "-Xms256m -Xmx1g"
    - name: Get processes list
      command: ps axf
