---
- hosts: test-node
  tasks:
    - name: "Install some distro required for Elastic"
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - which
        - java-1.8.0-openjdk
      become: true
    - name: Extract ElasticSearch 5.5.x archive
      unarchive:
        src: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.3.tar.gz
        dest: "{{ ansible_user_dir }}"
        remote_src: yes
    - name: Start ElasticSearch
      command: "{{ ansible_user_dir }}/elasticsearch-5.5.3/bin/elasticsearch -d"
      environment:
        ES_JAVA_OPTS: "-Xms256m -Xmx1g"
    - name: Get processes list
      command: ps axf
