---
- hosts: test-node
  tasks:
    - name: Display passed var test_var
      debug:
        msg: "{{ test_var }}"

    - name: Set test_var
      zuul_return:
        data:
          test_var: "modified"
